cameras:
  - id: front_door
    name: Front door
    rtsp_url: rtsp://user:password@192.168.1.10:554/stream1
    enabled: false
    input_args:
      - -rtsp_transport
      - tcp
      - -stimeout
      - "5000000"
    output_args:
      - -an
      - -c:v
      - copy

  - id: warehouse
    name: Warehouse
    rtsp_url: rtsp://user:password@192.168.1.11:554/stream1
    enabled: false
